version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:express_app@db:3306/express_app_db
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=express_app
      - MYSQL_DATABASE=express_app_db
      - MYSQL_PASSWORD=express_app
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexpress_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 